spring.datasource.url=jdbc:mysql://localhost:3306/tracker_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=nnm24cs168
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=mySecretKeyForCodingTrackerProjectThatIsLongEnoughForHS256Algorithm
app.jwt.expiration-ms=86400000
server.port=8080
github.api.token=ghp_yourGitHubPersonalAccessTokenHere
github.api.base-url=https://api.github.com
leetcode.api.base-url=https://leetcode-stats-api.herokuapp.com
scheduler.cron=0 0 1 * * ?
spring.main.allow-circular-references=true